### PR TITLE
Use digests when generating flow interfaces

### PR DESCRIPTION
**Pull request by stackptr**
## Task

[Use digests when generating flow interfaces](https://app.asana.com/0/0/1204229195748512/f)

### Convert package to TypeScript

Adds a `tsconfig.json` and various dependencies for a rewrite in TypeScript.

### Cache digests when generating interfaces

Defines a `Digest` to compute when generating a Flow interface from a TypeScript interface, which is then written to a cache on disk. Subsequent interface generation compare the digest written in the cache to the digest of the TypeScript interface if there is already a Flow interface present. If the digests match, generating the Flow interface is skipped.

Ajv is used to define the schema of digests that are serialized to the cache and then parsed into TypeScript types.

### CODE REVIEW

**Comment by stackptr** [comment]
This is tested working locally:
- Point package in megarepo to cloned `@freckle/gen-flow` repo checked out with this branch
- Run `yarn` to update lockfile
- Remove `lib` and run `yarn build:lib` to verify that interfaces are generated and `.genflowcache` is written
- Update a TypeScript module such that the interface generated by `tsc` will change (i.e., rename a type identifier in an export)
- Run modified `yarn build:lib` that does not include `yarn clean:lib` in the script
- Build is much faster; Flow interface for corresponding updated TypeScript module has expected change

I'm testing the CI use case in this PR: https://github.com/freckle/megarepo/pull/26106

**Comment by stackptr** [comment]
Seems to work as expected in CI: https://github.com/freckle/megarepo/pull/26106#issuecomment-1480552689

**Review by z0isch — APPROVED** [review]
Looks really neat! I do worry a bit about all the usual "caching is a hard problem" issues when rolling our own cache, but I guess the only issue could be a loss in type safety in flow due to an interface not getting updated?

It feels like something that would likely be caught during development with a `What the heck I just updated the type in TS and it's not updating in flow???` and not something that would break in production. 

Nice work!

**Comment by z0isch** [comment]
> * Build is much faster; Flow interface for corresponding updated TypeScript module has expected change

I wonder how much of a speedup this actually is!? Seems like something that could help morale and should be widely publicized- I know I'm pretty depressed about the speed of compiling our frontend right now 😢

**Review by luckysoni — APPROVED** [review]
Thank you for working on this! As AJ mentioned, the dev experience is really frustrating currently, this sure will help a lot!

**Comment by stackptr** [comment]
> > * Build is much faster; Flow interface for corresponding updated TypeScript module has expected change
> 
> I wonder how much of a speedup this actually is!? Seems like something that could help morale and should be widely publicized- I know I'm pretty depressed about the speed of compiling our frontend right now 😢

The difference is pretty dramatic. On CI, the first build with no cache still takes 10 minutes, but from a partial cache it takes under 2 mins.

**Pull request merged**
